### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by anrom7** [zoriankaaa/homeworks#1]
Звідки беруться дані? Ідея добра але або десь треба брати дані і з ними працювати або придумувати свою систему параментрів їх збереження та роботи з ними.
Тема: Обробка даних системи контролю тварин.

**Comment by zoriankaH** [comment]
> Звідки беруться дані? Ідея добра але або десь треба брати дані і з ними працювати або придумувати свою систему параментрів їх збереження та роботи з ними.
> Тема: Обробка даних системи контролю тварин.

Дякую! Вже найшла декілька джерел, зараз працюю над цим.
